language: node_js
node_js:
- '5'
- '5.1'
- '4'
- '4.2'
- '4.1'
- '4.0'
- iojs
install:
- npm install
script: npm run coverage
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  skip_cleanup: true
  email: "postalcodesjs@gmail.com"
  api_key:
    secure: CuhDn26PrOS2L/vGf/rO+kVYxHyDnOoahtW7lmh5/x/qM1XLYSK2TMOFsDHftKWshtBBrYm8OJxZI8S+U/tsGWFlgxhzlGglF2wgNCEOcU790CHYxV9o0RCHMX6OHe76JZFjq8SKJejZcSP8+5faaKeYL8Hr9Q/I+A/P666z6IIQJ4Cg77qO1C6ZdOMGpgXUuTTZF+IFhaskB72sjSE66XGI1VJachR9LS5QQHuiEslVKeadikLFLmIdb1m7l0I89P4QprVZQzWPAoPpEaKt+EZr82wQYlBOXQynwtTZY6MO6Lf9slIcBfB5nFTCkgRg7S4xjMT71X6ZlGlGhX5ZEjNlrLAAYZwnUkl6m8IS5LEpThIydPxNSuhx9OSUstfv/p0Jx1H47+BpYRUKhF+6n8ht9OQ+M1Om/8jgReR4P39aBpYtdCqZmr9mvh4k14/f+598mpzh/bs4lIjaaEq0q1BgH9TEH5vPPKFBpsV+RassNQOOAiXMXtG0KHp49YUMidLr7rBz/RWXo09kQ49pV14KJNvEkvipov5tLS9fGkWsWjtQn29RebB1EB2FTHOFxaASbHO6HwgTtOi8pz0hifOVYeZo9htYZWr2bk24K1Pt4e1e6IVOxhXLKC8y5dFGgWXURwvxr/DJOn722N90XaUhebImQgW4RZ5zb4vpHOs=
  on:
    branch: master