language: node_js
node_js:
- '10'
- '8'
- '6'
- '5'
- '4'
install:
- npm install
script: npm run coverage
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  skip_cleanup: true
  on:
    branch: master
  email: PostalCodesJS@cimpress.com
  api_key:
    secure: HSwroYsdKJQeS3SufkAGdUsYeTgdzj92Yfet2SvOEGkF926RCGnf0zOc0aPGfD7YEiQioiQDraO+14dyAehAU/AP9iqiSj4s74XP5Jabsvwv4cT6vzsrwFink6uWW89+hgdJRnjub2VPMZiBq7OHRnEbs3jTnFmK1yxxg6dJHvH8uGpVudjULJzBVh+DWIHtpB5k0VURwLNTP/M2q/4e1sYieJsnm/L9SHWT4DcbMiWDC0ljSmBBb57zHA5z96b5+JssDUMadQgMf8+iSHAwcVWL/BE374cp1Y2Bm43trU8NNx91Xl1BX7Hbv6BP+pu+bvJMfZXQRQW+J87mgVOqxFCXDX/MBvlpMMkBiYPGdQCnDSWu9L5Y8W0CfyGH+BiarZ8ntrb9ZrSPUZOw0E+hA7ZrfGuDw+7egQs2WoKhhfQudWKA07tS9BTQnULnjamOPJircPEJ/HyN9oUtpB9nHk1W8z8R7vxD1MwKskebwKnI0wXz17tvMPyx23pDZA7iW7dhqKZxrALSfYWKl8iAzqoshOeXJdjgox+sOxcPz3zTi/OVKpN0fDwT7GqCenfeNIy9kh3BMS9JXQfPAsP2gF86GvgPzxJC8UvMIhoTay/agzP5f0f0/ASUs5qHeTBgjoM51OT+B7hajrLf+9PKyqDLblVzXyXYTpLnyVDIZfw=
