language: node_js
node_js:
- '8'
- '6'
- '5'
- '4'
- iojs
install:
- npm install
script: npm run coverage
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: ivan.stanishev@gmail.com
  skip_cleanup: true
  on:
    branch: master
  api_key:
    secure: gUu40/AFVVGy3sbqZjvyBdDhagGrvixrW9zeCVJjkc5zJYZbKm/YItfbNCbrPjvBtB0602zna3NFEgVSN5hybRXz6Nfl8B5aYi9ufV62jwuqIMr9bk00n/ywj5HJvd7f83NLuNdSLoncouNysxklImhXsx48OcSdV8eJSLAeCcSJ2AkWSDJqqzgcPg19GbxfV42CYMyeoH6g4Vy1rVjDkrDEDdrd+Xnt+mtGCsDd+oLwW0HzYa27S0ePjri+gV6RktpILyhsQ2o2stl+rteLWbccdudeLz05eocWDemdc3i+C43n7KOm7IbrpckChaYT9VVzwSEV2aAHDhVaHkvjTtQzwsGEIhYE8AGlLTzc9FgYtsewPkbG7oJHmjziv/gzXagelML+I+Hs8IR3rJlS/c1yR43iBb1gb3cTQrRsB5bKLgFJcYguNwBQzalfin0nzOCu+1E51eQDpOgG5visjK0MZSr7olnIAxzV9kMMj3eeLEtfiq/0CRSd4cIAymKn/U0DG3DdNdWGhViCu+TxmaFm+eyn8pddt6L5h4MJF20RRPs5W1L6QBhFtVWpnfMk7XGZ/03BtfJ8Swiq+hYrRAUM1Dankke1GDfEsKjToC3VxThkvtnm5GK4nchzWXDnv+ov0y4vPP/yXFpVrDwWV9qIxkUvXpSCzOhLSoD81wM=
